project:
  type: website
  output-dir: docs
execute:
  freeze: true
website:
  google-analytics: "G-1S2DDJMWQ6"
  title: "Basar Sohail Chowdhury"
  favicon: favicon/favicon-32x32.png
  open-graph:
    locale: en_US
  twitter-card:
    image: street.jpg
    card-style: summary
    creator: "@sohailchd"
  site-url: https://sohailchd.github.io/sweblogs/
  description: "Blog for software engineering and data science"
  navbar:
    right:
      - text: "About Me"
        file: about.qmd
      - text: "Blog"
        file: index.qmd
  page-footer: 
    left: "Basar Sohail Chowdhury" 
    right: 
      - icon: linkedin
        text: LinkedIn
        href: https://www.linkedin.com/in/sohailchd/
      - icon: github
        text: Github
        href: https://github.com/sohailchd
      - icon: twitter
        text: Twitter
        href: https://twitter.com/sohail_twt
      - icon: rss
        text: Blog RSS
        href: blog.xml
format:
  html:
    css: styles.css
    theme: 
      light: cosmo
      dark: cyborg

