name: Deploy Quarto Site

on:
  push:
    branches:
      - main  # Set to your default branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.x'  # Set the R version you need

      - name: Install Quarto
        uses: quarto-dev/quarto-actions@v2
        with:
          version: 'latest'

      - name: Install dependencies
        run: |
          R -e 'install.packages(c("rmarkdown", "knitr", "quarto"), repos="https://cran.rstudio.com/")'
          sudo apt-get install -y pandoc

      - name: Render Quarto Site
        run: |
          quarto render site.qmd  # Replace with your site file

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Set to the output directory of your Quarto site
